### ISSUE TITLE
Support for missing features used in SICP code examples?

### ISSUE THREAD

**Issue by pgbovine** [eliben/bobscheme#3]
Hi,

First off, great job on this project! I'm starting to play around with the code base now and running the code from the SICP website:
https://mitpress.mit.edu/sicp/code/index.html

I noticed that the Bob interpreter (invoked via interpret_file.py) seems to be missing several features that are present in the SICP code examples above. Most notably:
  - the '/' operator
  - string literals like "hello"
  - floating-point literals like 0.5

Do you have plans to add those to Bob? Thanks.

**Comment by eliben** [comment]
I think adding features like this should be pretty easy. I don't have all of them because my goal wasn't full completeness but rather build the interpreter/compiler/VM infrastructures such features can then be added on.

So, while myself I don't have plans for this any time in the near future, I'll be happy to accept patches that implement these things.

[P.S. I *think* division is implemented for integers]

**Comment by pgbovine** [comment]
Thanks! I may take a crack at this over the next few months if I have time. In any case, best wishes with this project and others.
